// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttkvkvctbakfgzhrwaev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0a3ZrdmN0YmFrZmd6aHJ3YWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjMyNDUsImV4cCI6MjA2ODMzOTI0NX0.hgop-b-x5D4hEMp-GSN_osaIZCF62swMSXJiD1afl4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});