// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjjwvksbetogxpciowdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indqand2a3NiZXRvZ3hwY2lvd2R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTU1MTYsImV4cCI6MjA2ODE3MTUxNn0.psYqi3wxSX8CD6NL1fC9foKmloFdHXBYdggNtoIq2B0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});